import Header from './components/Header';
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ weight: ["400", "700"], subsets: ['latin'] })

export const metadata = {
  title: 'Skillhub',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} box-border min-h-screen bg-dark text-white sm:p-12 p-6`}>
          <Header />
          {children}
      </body>
    </html>
  )
}
